name: Build

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - develop
      - main

jobs:
  build_test:
    name: Build Status
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "securepassword"
          POSTGRES_DB: trailer_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d trailer_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js with v23.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.1.0'

      # Install Yarn
      - name: Install Yarn
        run: npm install --global yarn

      # Install dependencies with Yarn
      - name: Install dependencies
        run: yarn install

      - name: Setup environment variables
        run: |
          echo "NODE_ENV=test" >> $GITHUB_ENV
          echo "APP_PORT=8080" >> $GITHUB_ENV
          echo "DB_TEST_NAME=trailer_test" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=securepassword" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "LOG_LEVEL=debug" >> $GITHUB_ENV

      # Run lint with Yarn
      - name: Run lint
        run: yarn lint

      - name: Run migrations
        run: yarn db:migrate

      - name: Run tests
        run: yarn clean && yarn test
