name: Lint and Test

on:
  push:
    branches:
      - main
      - develop
      - staging
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  lint-and-test:
    name: Run Lint and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js with v23.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.1.0'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint
      - name: Run lint
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm run test
